### ISSUE TITLE
build-dependency missing: dh-strip-nondeterminism 

### ISSUE THREAD

**Issue by Marqin** [collectd/pkg-debian#4]
Hi, when I've tried to build that package ( on my fully up-to-date jessie ), after `apt-get build-dep` `debuild` said that `dh-strip-nondeterminism` package is not installed. ( installing via `apt-get` helped ofc ).

**Comment by Marqin** [comment]
Hmm, it looks like `dh-strip-nondeterminism` is included in build-deps. So probably it's a bug of debuild on jessie.

**Comment by mfournier** [comment]
The master branch targets sid. There are plans to package 5.5.0 for jessie-backports. If you figure out the changes needed to build 5.5.0-3 for Jessie, your welcome to share them here. Thanks!

**Comment by Marqin** [comment]
This are steps I had performed in my Jessie chroot:

```
sudo apt-get install build-essential
git clone https://github.com/collectd/pkg-debian.git
cd pkg-debian
sudo apt-get build-dep collectd
debuild -b -us -uc  # FAILED with error that dh-strip-nondeterminism is not installed
sudo apt-get install dh-strip-nondeterminism
debuild -b -us -uc  # SUCCESS!
cd ..
sudo dpkg -i collectd* libcollectd*
```

And collectd is working OK :ok_hand:

**Comment by mfournier** [comment]
Closing, as 5.5.0 is now available in jessie-backports.
