### ISSUE TITLE
Not working on systems using comma as decimal mark.

### ISSUE THREAD

**Issue by Marqin** [collectd/pkg-debian#5]
In log there is:
`[2015-09-17 16:22:22] rrdtool plugin: rrd_update_r (/var/lib/collectd/rrd/outsider/load/load.rrd) failed: /var/lib/collectd/rrd/outsider/load/load.rrd: conversion of '1,41' to float not complete: tail ',41'`

This is because `,` is set as decimal mark in Debian with PL or DE ( and probably some other too ) locales.

There is  [some workaround](https://github.com/collectd/collectd/issues/1237) for that on collectd Github, but it's ignored by upstream devs... Could you maybe fix it in Debian version of collectd?

**Comment by octo** [comment]
This is not specific to the Debian package. See collectd/collectd#1237 for more information.
