### ISSUE TITLE
Unable to install on debian whizzy

### ISSUE THREAD

**Issue by adkhare** [collectd/pkg-debian#7]
dpkg-checkbuilddeps: Unmet build dependencies: dh-systemd (>= 1.5) dh-strip-nondeterminism libatasmart-dev libcap-dev libhiredis-dev libi2c-dev liblvm2-dev libmnl-dev libow-dev libprotobuf-c-dev librdkafka-dev libsigrok-dev (>= 0.2~) libudev-dev default-jdk

**Comment by tokkee** [comment]
The master branch (which, I suppose, you're using) is targeted at Debian unstable and testing. For stable releases, use the respective backport branch, e.g. [wheezy-backports-sloppy](/collectd/pkg-debian/tree/wheezy-backports-sloppy) in your case.
